// Code generated by go-swagger; DO NOT EDIT.

package comics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelNewsUpdated model news updated
//
// swagger:model model.NewsUpdated
type ComicsCreated struct {

	// success
	Success bool `json:"created,omitempty"`
}

// Validate validates this model news updated
func (m *ComicsCreated) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model news updated based on context it is used
func (m *ComicsCreated) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ComicsCreated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComicsCreated) UnmarshalBinary(b []byte) error {
	var res ComicsCreated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
